### ISSUE TITLE
ios 编译的问题

### ISSUE THREAD

**Issue by wang820203420** [genixtec/ios-dicom-image-processing#1]
尊敬的工程师：
       我在编译ios oc 下的 imebra 的时候遇到了问题：
gupodeMac-mini:~ gupo$ cd /Users/gupo/Desktop/imebra_for_ios 
gupodeMac-mini:imebra_for_ios gupo$ cmake /Users/gupo/Desktop/imebra_4_4_0_2 -DIOS=SIMULATOR
Using ICONV (default)
IOS SDK ROOT: xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: SDK "iphonesimulator" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'iphonesimulator'
-- CLANG detected, adding compile flags
-- OBJC INCLUDE:/Users/gupo/Desktop/imebra_4_4_0_2/objectivec/include
-- GNU INCLUDE:
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/gupo/Desktop/imebra_for_ios

请问怎么编译？

**Comment by shanmugasanthosh7** [comment]
Check with your iOS SDK
